Boojey Violet
author: @ruckthyst
email: boojeyviolet@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to Boojey Violet. Peace, colour, art and some snazzy sustainable threads 
# social links
twitter_username: @boojeyviolet
github_username:  @ruckthyst
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima 
